version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions-patch:
        patterns:
          - "*"
        update-types:
          - patch
      github-actions-minor-major:
        patterns:
          - "*"
        update-types:
          - minor
          - major

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    cooldown:
      default-days: 7
    groups:
      uv-patch:
        patterns:
          - "*"
        update-types:
          - patch
      uv-minor-major:
        patterns:
          - "*"
        update-types:
          - minor
          - major

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      pre-commit-patch:
        patterns:
          - "*"
        update-types:
          - patch
      pre-commit-minor-major:
        patterns:
          - "*"
        update-types:
          - minor
          - major
